background {
    path = ~/wallpapers/wallhaven-md58xk_2560x1440.png
    blur_passes = 2
    blur_size = 6
    brightness = 0.25
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 80
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    size = 200, 50
    outline_thickness = 2
}
