
workspace = 2, on-created-empty:firefox

# Special

bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic
workspace = special:scratchpad, on-created-empty:kitty

